---
title: "prepare_hic_feature"
author: "Yunqi Yang"
date: "8/4/2020"
output: html_document
---



## prepare for HiC feature 
```{r  }

load("/Users/nicholeyang/Desktop/Rotation2/data/hic_eqtl.RData")

```


```{r  }

head(hic_eqtl)


```

```{r  }

## remove NA genes
hic_eqtl2 = hic_eqtl[!is.na(hic_eqtl$baitName), ]

## split those with several bait genes 
bait_gene = strsplit(as.character(hic_eqtl2$baitName), ';')
ngenes = lapply(bait_gene, function(x) length(x))

index_list = c()
for(i in 1:dim(hic_eqtl2)[1]){
  index = rep(i, ngenes[[i]])
  index_list = c(index_list, index)
}

hic_eqtl3 = hic_eqtl2[index_list, ]
hic_eqtl3$bait_gene = unlist(bait_gene)

```


## load training data
```{r  }

load("/Users/nicholeyang/Desktop/gene_level_fine_mapping/data/training.RData")

## remove NAs
dat = rbind(train_pos_all, train_neg_all)
NAs = apply(dat, 1, function(x) sum(is.na(x)))
dat = dat[NAs == 0, ]

```


```{r  }

## add variable snp_loc38 to training data 
var_loc = strsplit(as.character(dat$variant_id), '_')
dat$snp_loc38 =  paste(unlist(lapply(var_loc, function(x) x[1])), unlist(lapply(var_loc, function(x) x[2])), sep = ':')

## add variable snp_loc38 to hic_eqtl3
var_loc = strsplit(as.character(hic_eqtl3$loc_38map), '-')
hic_eqtl3$snp_loc38 = unlist(lapply(var_loc, function(x) x[1]))

```


## restrict hic_eqtl to coding genes
```{r  }

coding_gene_list = read.table('/Users/nicholeyang/Desktop/Rotation2/data/coding_gene_list.txt', header = TRUE)

coding_gene_list$gene_name = coding_gene_list$Approved_symbol
hic_eqtl3$gene_name = hic_eqtl3$bait_gene
hic_eqtl4 = merge(coding_gene_list, hic_eqtl3, by = 'gene_name', all = FALSE)

```

```{r  }

dim(hic_eqtl4)[1]

```



## add HiC annotations to eqtl gene-snp pairs 

```{r  }

index_in_hic = c()

for(i in 1:dim(dat)[1]){
  index = which(dat[i, ]$gene_name == hic_eqtl4$gene_name & dat[i, ]$snp_loc38 == hic_eqtl4$snp_loc38)
  index_in_hic = c(index_in_hic, index)
}

length(index_in_hic)

```

```{r  }

train_hic = hic_eqtl4[index_in_hic, c("gene_name", "Mon", "Mac0", "Mac1",  "Mac2", "Neu",
                                         "MK", "EP", "Ery", "FoeT", "nCD4", "tCD4", "aCD4",          
                                         "naCD4", "nCD8", "tCD8", "nB", "tB","snp_loc38")]

dat_add_hic = merge(dat, train_hic, by = c('gene_name', 'snp_loc38'), all = TRUE)
```

```{r }

## check NAs
Nas = apply(dat_add_hic, 2, function(x) sum(is.na(x)))
Nas

## replace NAs with 0
dat_add_hic[is.na(dat_add_hic)] <- 0
```


```{r  }

## binary the hic features
cols = c("Mon", "Mac0", "Mac1",  "Mac2", "Neu", "MK", "EP", "Ery", "FoeT",
         "nCD4", "tCD4", "aCD4", "naCD4", "nCD8", "tCD8", "nB", "tB")


for( i in 1:length(cols)){
  dat_add_hic[, cols[i]] = ifelse(as.numeric(as.character(dat_add_hic[, cols[i]])) >5, 1, 0)
}

save(dat_add_hic, file = '/Users/nicholeyang/Desktop/gene_level_fine_mapping/data/train_add_hic.RData')
```









