---
title: "eQTL data processing"
author: "Yunqi Yang"
date: "7/1/2020"
output:
  html_document: default
  pdf_document: default
---

## create positive gene-SNP set
```{r  eval = FALSE}
# unix command 
srun --pty --mem 5G -t 01:00:00 /bin/bash
module load R
R

```

```{r  eval = FALSE}

setwd("/home/yunqiyang/summer_rotation/whole_blood_eqtl")
dt = read.table("Whole_Blood.variants_pip.txt", header = TRUE)

dim(dt) # 420370 6
sum(is.na(dt)) # 0
```

```{r  eval = FALSE}

setEPS()
postscript("pip_summary.eps")
hist(dt$pip)
dev.off()

```

```{r eval = FALSE}

length(unique(dt$gene)) # 15252
sum(dt$pip>0.5) # 5080
sum(dt$pip>0.8) # 2751
sum(dt$pip>0.1) # 28559

```

```{r eval = FALSE}

# save data 
dt_pos = dt[dt$pip>0.5, ]
dt_neg = dt[-(dt$pip>0.5), ]

save(dt_pos, file = 'SNPs_causal.RData')
save(dt_neg, file = 'SNPs_control.RData')

```



## processing gene-SNP positive set
```{r  }

# load fine-mapping positive set
load("/Users/nicholeyang/Desktop/Rotation2/gene-level fine mapping/data/SNPs_causal.RData")

```


### split snp info into multiple columns
```{r  }

dt_pos$variant_id = as.character(dt_pos$variant_id)
var_position = strsplit(dt_pos$variant_id, '_')

chr = rep(NA, length(var_position))
SNP_loc = rep(NA, length(var_position))
  
for (i in 1:length(var_position)){
  chr[i] = var_position[[i]][1]
  SNP_loc[i] = var_position[[i]][2]
}



```

```{r  }

chr = unlist(lapply(var_position, function(x) x[1]))
dt_pos$SNP_chr = gsub('\\D','', chr)
dt_pos$SNP_loc = unlist(lapply(var_position, function(x) x[2]))

```

### create gene_id without gene version number
```{r  }

gene_seg = strsplit(as.character(dt_pos$gene), '.', fixed = TRUE)
dt_pos$gene_id = unlist(lapply(gene_seg, function(x) x[1]))

```


```{r  }

head(dt_pos)

```

```{r  }

save(dt_pos, file = 'dt_pos_processed.RData')

```

