---
title: "Exploratory analysis for gene-level fine-mapping"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Investigations into the factors that can predict the target genes of the SNPs. 

Follow the links below to browse the results.


+ [eQTL data processing](eqtl_process.html)

+ [Add tss information to data](add_tss.html)

+ [Merge ANNOVAR with causal set](gene_snp_annotation.html)

+ [Create training data](create_training_set.html)

+ [Model fitting](model_fitting.html)

+ [Distance function](dist_functions.html)

+ [Process HiC data](hic_raw.html)

+ [Add HiC feature to training data](add_hic_feature.html)

+ [Add ATAC feature to training data](atac_eqtl.html)

+ [Model HiC data](model_hic.html)

+ [Model ATAC data](model_atac.html)

+ [Model all features](fit_all_feature.html)

+ [Assess only distal observations](assess_distal_observation.html)

+ [Assess only distal observations,filtered](assess_distal_observation_filtered.html)
