---
title: "model_fitting"
author: "Yunqi Yang"
date: "7/17/2020"
output:
  pdf_document: default
  html_document: default
---

```{r  }

library(ggplot2)
library(dplyr)
require(PRROC)

```


```{r  }

load("/Users/nicholeyang/Desktop/gene_level_fine_mapping/data/training.RData")

```

```{r  }

## remove NAs
dat = rbind(train_pos_all, train_neg_all)
NAs = apply(dat, 1, function(x) sum(is.na(x)))
dat = dat[NAs == 0, ]


```


## data overview
```{r  }

head(dat)

```

```{r  }

# number of observations in the dataset 
dim(dat)[1]

sum(dat$y == 1)  # positive pairs
sum(dat$y == 0)  # negative pairs 

```


## proportion of features 

```{r  }
par(mfrow = c(1,2))

# proportion of features in the positive set
tot_count = apply(dat[dat$y==1, c(3:7)], 2, function(x) sum(x == 1))
barplot(tot_count/dim(dat[dat$y==1, ])[1], las = 2, main = 'feature proportion in positive set')

# proportion of features in the negative set
tot_count = apply(dat[dat$y==0, c(3:7)], 2, function(x) sum(x == 1))
barplot(tot_count/dim(dat[dat$y==0, ])[1], ylim = c(0, 0.01), las = 2, main = 'feature proportion in negative set')

```

## by variable logistic regression
```{r  }

fit1  = glm(y ~ UTR5, data = dat, family = "binomial")
fit2 = glm(y ~ UTR3, data = dat, family = "binomial")
fit3 = glm(y ~ exon, data = dat, family = "binomial")
fit4 = glm(y ~ intron, data = dat, family = "binomial")
fit5 = glm(y ~ upstream, data = dat, family = "binomial")


summary(fit1)
summary(fit2)
summary(fit3)
summary(fit4)
summary(fit5)
```


## fit all features
```{r }

fit6 = glm(y ~ UTR5 + intron + upstream + exon, data = dat, family = "binomial")
summary(fit6)

fit7 = glm(y ~ UTR5 + UTR3 + intron + upstream + exon, data = dat, family = "binomial")
summary(fit7)

```

## AIC criteria and deviance: the smaller the better
$$AIC=-2\log L(\theta)+2k$$
$$deviance=-2\log L(\theta)$$


## calculate prediction accuracy: train-test split

```{r  }

set.seed(1)
n = dim(dat)[1]
indx = sample(1:n, round(2*n/3), replace = FALSE)
train = dat[indx, ]
test = dat[-indx, ]

```

```{r  }

# build model on the training set
fit.all = glm(y ~ UTR5 + UTR3 + intron + upstream + exon, data = train, family = "binomial")

# evaluate on the test set 
pred.probs=predict(fit.all,test,type="response")


```

```{r  }

plot(pred.probs, type = 'p', pch = '.')

```



### classification accuracy
```{r  }

glm.pred = rep(0, length(pred.probs))
glm.pred[pred.probs>0.5]= 1
table(glm.pred, test$y)
```



### plot ROC-AUC PR-AUC
```{r  }

fg <- pred.probs[test$y == 1]
bg <- pred.probs[test$y== 0]

# ROC Curve    
roc <- roc.curve(scores.class0 = fg, scores.class1 = bg, curve = T)
plot(roc)

# PR Curve
pr <- pr.curve(scores.class0 = fg, scores.class1 = bg, curve = T)
plot(pr)

```


## play around tss feature 

```{r  }

summary(dat$tss_dist_to_snp)
summary(dat[dat$y==1, ]$tss_dist_to_snp)  # dist_to_tss in positive set 
summary(dat[dat$y==0, ]$tss_dist_to_snp)  # dist_to_tss in negative set 

```

```{r  }

# change fill and outline color manually 
ggplot(dat, aes(x = tss_dist_to_snp)) +
  geom_histogram(aes(color = as.factor(y), fill = as.factor(y)), 
                position = "identity", bins = 50, alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))



boxplot(tss_dist_to_snp ~ y, data = dat)


```


### exponential decay: exp(-d/sigma) 

```{r  }

sigma = 1e5
dat$weight = exp(-dat$tss_dist_to_snp/sigma)

```

```{r  }

# change fill and outline color manually 
ggplot(dat, aes(x = weight)) +
  geom_histogram(aes(color = as.factor(y), fill = as.factor(y)), 
                position = "identity", bins = 50, alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))



boxplot(weight ~ y, data = dat)


```


```{r  }

# fit raw tss
fit.raw.tss  = glm(y ~ tss_dist_to_snp, data = dat, family = "binomial")
summary(fit.raw.tss)


# fit exponential decay: 
fit.exp.tss  = glm(y ~ weight, data = dat, family = "binomial")
summary(fit.exp.tss)

```


## add weight to all feature logsitic regression and plot ROC/PR-AUC 

```{r  }

# split data in the same way
set.seed(1)
n = dim(dat)[1]
indx = sample(1:n, round(2*n/3), replace = FALSE)
train = dat[indx, ]
test = dat[-indx, ]

# fit model and evaluate performance
fit.all = glm(y ~ UTR5 + UTR3 + intron + upstream + exon + weight, data = train, family = "binomial")
summary(fit.all)

pred.probs=predict(fit.all,test,type="response")
glm.pred = rep(0, length(pred.probs))
glm.pred[pred.probs>0.5]= 1
table(glm.pred, test$y)

```


```{r  }

fg <- pred.probs[test$y == 1]
bg <- pred.probs[test$y== 0]

# ROC Curve    
roc <- roc.curve(scores.class0 = fg, scores.class1 = bg, curve = T)
plot(roc)

# PR Curve
pr <- pr.curve(scores.class0 = fg, scores.class1 = bg, curve = T)
plot(pr)

```
